## Упражнения по библиотеке Numpy

In [21]:
import numpy as np

In [22]:
from numpy import random
x = random.randint(20, size=(10))
x

array([ 4, 18,  2,  7, 14, 14, 10,  4,  3,  3])

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [23]:
from numpy import random


x[(3 < x) & (x < 8)] *= -1

x

array([-4, 18,  2, -7, 14, 14, 10, -4,  3,  3])

**2.** Заменить максимальный элемент случайного массива на 0

In [24]:
x[x.argmax()] = 0
x

array([-4,  0,  2, -7, 14, 14, 10, -4,  3,  3])

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [25]:
import numpy as np

def cartesian(array):
    arr=np.vsplit(array,2)
    arr1 = arr[0]
    arr2= arr[1]
    combinations = np.array(np.meshgrid(arr1, arr2)).T.reshape(-1,2)
    print(combinations)
    
example_array = np.arange(8).reshape(2, 4)
cartesian(example_array)

[[0 4]
 [0 5]
 [0 6]
 [0 7]
 [1 4]
 [1 5]
 [1 6]
 [1 7]
 [2 4]
 [2 5]
 [2 6]
 [2 7]
 [3 4]
 [3 5]
 [3 6]
 [3 7]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [40]:
A = np.random.randint(0,5,(8,3))
A

array([[3, 2, 1],
       [0, 0, 4],
       [3, 1, 0],
       [3, 4, 3],
       [2, 1, 4],
       [0, 1, 0],
       [1, 0, 4],
       [3, 0, 1]])

In [41]:
B = np.random.randint(0,5,(2,2))
B

array([[2, 2],
       [3, 2]])

In [42]:
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)



[0 3 4]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [46]:
Z = np.random.randint(0,3,(10,3))
print(Z)

[[1 1 1]
 [2 2 2]
 [0 0 0]
 [2 1 1]
 [0 2 1]
 [2 1 0]
 [2 2 1]
 [0 0 2]
 [0 2 0]
 [2 1 0]]


In [47]:
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[2 1 1]
 [0 2 1]
 [2 1 0]
 [2 2 1]
 [0 0 2]
 [0 2 0]
 [2 1 0]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [65]:
N = np.random.randint(0,3,(10,3))
print(N)

[[1 0 0]
 [1 2 1]
 [0 2 1]
 [1 1 0]
 [1 0 2]
 [0 1 2]
 [2 1 1]
 [2 1 2]
 [2 1 2]
 [2 1 2]]


In [66]:
def unique_rows(a):
    a = np.ascontiguousarray(a)
    unique_a = np.unique(a.view([('', a.dtype)]*a.shape[1]))
    return unique_a.view(a.dtype).reshape((unique_a.shape[0], a.shape[1]))

print(unique_rows(N))

[[0 1 2]
 [0 2 1]
 [1 0 0]
 [1 0 2]
 [1 1 0]
 [1 2 1]
 [2 1 1]
 [2 1 2]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [67]:
b = np.random.randint(0,10,(3,3))
print(b)


print(sum(np.diagonal(b)))

[[6 3 3]
 [5 5 5]
 [4 0 8]]
19


In [68]:
n = 3
a = [[6,3,3],[5,5,5],[4,0,8]]
d_sum = sum([a[i][j] for i in range(n) for j in range(n) if i==j]) 
d_sum

19

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [72]:
A = np.array([1, 2, 2, 2])
B = np.array([4, 2, 1, 2]) 

In [73]:
(unique, counts) = np.unique(A, return_counts=True)
A = np.asarray((unique, counts)).T

(unique, counts) = np.unique(B, return_counts=True)
B = np.asarray((unique, counts)).T

print(np.array_equal(A,B))

False


In [74]:
from collections import Counter

l1 = [1,2,2,4]
l2 = [4,2,1,2]
print(Counter(l1) == Counter(l2))

True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [75]:
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
print(max(x[i] for i in range(1, len(x)) if not x[i-1]))

5


In [76]:
y = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zero = y==0
print(y[1:][zero[:-1]].max())

5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [79]:
import numpy as np
x = np.array([2, 2, 2, 3, 3, 3, 5])

def rle(inarray):
        ia = np.asarray(inarray)                
        n = len(ia)
        if n == 0: 
            return (None, None, None)
        else:
            y = ia[1:] != ia[:-1]              
            i = np.append(np.where(y), n - 1)   
            z = np.diff(np.append(-1, i))       
            return(ia[i], z)
        
print(rle(x))

(array([2, 3, 5]), array([3, 3, 1], dtype=int64))


In [80]:
def rle_encode(in_list):
    out_list = [(in_list[0], 1)]
    for item in in_list[1:]:
        if item == out_list[-1][0]:
            out_list[-1] = (item, out_list[-1][1] + 1)
        else:
            out_list.append((item, 1))
    return out_list

print(rle_encode([2, 2, 2, 3, 3, 3, 5]))

[(2, 3), (3, 3), (5, 1)]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [81]:
from scipy.spatial.distance import cdist
a = [[1, 3, 27], [3, 6, 8]]
arr1 = cdist(a, a) 
  
print("Value of cdist is :", arr1) 

Value of cdist is : [[ 0.         19.33907961]
 [19.33907961  0.        ]]


In [82]:
import numpy as np

point1 = np.array((1, 3, 27))
point2 = np.array((3, 6, 8))

dist = np.linalg.norm(point1 - point2)

print(dist)

19.339079605813716


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [83]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [84]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [85]:
average_calories = np.average(calorie_stats)
average_calories

106.88311688311688

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [86]:
calorie_stats_sorted = np.sort(calorie_stats)[::-1]
calorie_stats_sorted

array([160., 150., 150., 140., 140., 140., 130., 130., 120., 120., 120.,
       120., 120., 120., 120., 120., 120., 120., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100.,  90.,  90.,
        90.,  90.,  90.,  90.,  90.,  80.,  70.,  70.,  50.,  50.,  50.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [87]:
median_calories = np.median(calorie_stats)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [88]:
nth_percentile = np.percentile(calorie_stats,4)
nth_percentile

70.0

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [89]:
more_calories = np.count_nonzero(calorie_stats[calorie_stats>60]) / np.count_nonzero(calorie_stats)
more_calories

0.961038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [90]:
calorie_std = np.std(calorie_stats)
calorie_std

19.35718533390827

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [167]:
# your code